site_name: MBARI Keras Classify
site_author: Danelle Cline
repo_url: "https://github.com/mbari-org/kclassify"
theme:
  name: material
  logo: imgs/mbari-logo.png
extra_css:
    - https://docs.mbari.org/css/mbari.css

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - MBARI Documentation: https://docs.mbari.org/
  - About: index.md
  - Installation: install.md
  - How to use in AWS: run_aws.md
  - How to use locally: run_local.md
  - Arguments: arguments.md
  - Change Log: CHANGELOG.md

copyright: Maintained by <a href="https://www.mbari.org/cline-danelle-e/">Danelle Cline</a>.

plugins:
    - search
