name: New Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
 semantic_release:
    runs-on: ubuntu-latest
    name: Runs semantic release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: semantic
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: docker push version
        if: steps.semantic.outputs.released == 'true'
        run: |
          export RELEASE_VERSION=$(echo ${{ steps.semantic.outputs.tag }} | cut -c 2-)
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} 
          docker buildx create --name mybuilder --platform linux/amd64,linux/arm64 --use
          docker buildx build -f docker/Dockerfile --push --platform linux/amd64,linux/arm64 -t mbari/kclassify:$RELEASE_VERSION --label IMAGE_URI=mbari/kclassify:$RELEASE_VERSION .
 push_readme_to_dockerhub:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: mbari/kclassify:latest
          provider: dockerhub
          short_description: 'Train an image classification model locally or AWS SageMaker using Keras.'
          readme_file: 'README.md'